//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomaticStoreKepper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int SuppliedId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Created_On { get; set; }
        public int Creted_By { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
